spring:
  application:
    name: student-service
  datasource:
    url: jdbc:mysql://localhost:3306/students?createDatabaseIfNotExist=true
    username: root
    password: Admin@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8082
  servlet:
    context-path: /student
